### PR TITLE
Improve unit testing by means of Tox and Coveralls

### PR DESCRIPTION
**Pull request by evilaliv3**
With this commit:
- test are now implemented using [Tox](https://tox.readthedocs.org/en/latest/)
- tests are now performed on all the relevant versions of twisted (12, 13, 14, 15)
- tests are now performed on all the relevant versions of python (2.7, 3.5, pypy, pypy3)
- code coverage is collected during tests and published on README.md and at https://coveralls.io/github/evilaliv3/twistar

### CODE REVIEW

**Comment by evilaliv3** [comment]
screenshot from 2016-01-04 04 28 34

**Comment by evilaliv3** [comment]
ok @bmuller, i've updated the readme badges making them point to your repository.

no you have simply to login on coveralls and activate coveralls on your repository.

**Comment by bmuller** [comment]
When I run `tox` I get an error:
```
GLOB sdist-make: /private/tmp/twistar/setup.py
coverage recreate: /private/tmp/twistar/.tox/coverage
coverage inst: /private/tmp/twistar/.tox/dist/twistar-1.3.zip
coverage installed: twistar==1.3,Twisted==15.5.0,wheel==0.24.0,zope.interface==4.1.3
coverage runtests: PYTHONHASHSEED='2194578734'
coverage runtests: commands[0] | coverage erase
ERROR: InvocationError: could not find executable 'coverage'
...
```

Also, I think `.coverage` and `.tox` should be added to the `.gitignore` file, right?

**Comment by evilaliv3** [comment]
let me check and i will be back to you

**Comment by evilaliv3** [comment]
here you go man!

**Comment by bmuller** [comment]
Thanks @evilaliv3!

**Comment by evilaliv3** [comment]
you are welcome @bmuller !

strangely the coveralls badge is not updating.

try to put this badge url that has a specifc query arg mentioning github and lets see if with the first real commit by you it will start working: 

```
[![Coverage Status](https://coveralls.io/repos/bmuller/twistar/badge.svg?branch=master&service=github)](https://coveralls.io/github/bmuller/twistar?branch=master)
```

**Comment by bmuller** [comment]
Yeah, I saw that - looks like there's no coverage info for the last commit - https://coveralls.io/builds/4632048

**Comment by evilaliv3** [comment]
i do not know what to say, have you logged into coveralls; it says something about it?

maybe my branch is magic and your is not!

**Comment by bmuller** [comment]
@evilaliv3 It took a bit to track down!  It was [this line](https://github.com/bmuller/twistar/commit/69e4312872f2294232fb9d34c9677eefe89ce649#diff-b91f3d5bd63fcd17221b267e851608e8R27) in the tox.ini, where `[testenv:coveralls]` should have been `[testenv:coverage]`.

**Pull request merged**
